//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
